### PR TITLE
Fix python version cfg

### PR DESCRIPTION
**Pull request by pejter**

### CODE REVIEW

**Comment by aviramha** [comment]
Hey, it seems that clippy had added a new warning that wasn't shown before (or is it relevant to the configuration being used now?)
Anyway, can you fix it?

**Comment by pejter** [comment]
Fixed the clippy warnings.

**Comment by aviramha** [comment]
Please remove the build.rs (which sets those env vars)

**Comment by aviramha** [comment]
image
We need to follow those instructions to have the supplemented PyO3 cfgs.

**Comment by pejter** [comment]
So why does it work without it at the moment? If the dependency isn't present and the flags are missing then something should fail, right? I tested the 3.6 version locally and it does indeed fail at import, so perhaps there should be a very basic python-level test suite in place to verify the API?

**Comment by aviramha** [comment]
@pejter It is odd. I'm working on adding a test to verify declaration works as desired.
https://github.com/aviramha/ormsgpack/pull/25

**Comment by aviramha** [comment]
It seems that it does fail. Your changes should fix it.

**Comment by aviramha** [comment]
Thanks!

**Pull request merged**
