### PR TITLE
Add support for Pydantic V2

### PR DESCRIPTION
**Pull request by exg**
See https://docs.pydantic.dev/latest/migration/

### CODE REVIEW

**Comment by aviramha** [comment]
Thanks for your contribution!
Please add tests, similar to what we have in https://github.com/aviramha/ormsgpack/blob/master/tests/test_pydantic.py

**Comment by exg** [comment]
> Thanks for your contribution! Before merging this, we need to add tests, similar to what we have in https://github.com/aviramha/ormsgpack/blob/master/tests/test_pydantic.py

What tests do you have in mind? The existing tests cover V2, and pass with my change. Note that the tests use pydantic 2, as the pydantic dependency is not pinned in `tests/requirements.txt`.

**Comment by aviramha** [comment]
erm, maybe have a flag in the CI for pydantic v1/v2 then test each ?

**Comment by aviramha** [comment]
Ah, my mistake - all is good then, just need DCO.

**Review by aviramha — APPROVED** [review]

**Pull request merged**
