### PR TITLE
Fix: Drop python 3.6 and support 3.11

### PR DESCRIPTION
**Pull request by onegreyonewhite**
##### Changelog:
- Add `.idea` to ignored files.
- Removed duplicate of `Programming Language :: Python :: 3.10`.
- Add information about Python 3.11 support.
- Add Python 3.11 to release.yml in github actions.
- Add support for maturin 0.13.
- Fix Clippy warnings and errors.
- Update ahash, pyo3 and pyo3-build-config.
- Change timezone which has different hours.
- Fix Github actions pip update.

#128

### CODE REVIEW

**Comment by aviramha** [comment]
Thank you. Can you add it to the release.yaml as well?

**Comment by onegreyonewhite** [comment]
> Thank you. Can you add it to the release.yaml as well?

@aviramha done. Also I've squashed the commits.

**Comment by aviramha** [comment]
Awesome.

**Comment by aviramha** [comment]
I approved the CI. If you want to become maintainer of this, let me know.

**Comment by onegreyonewhite** [comment]
> I approved the CI. If you want to become maintainer of this, let me know.

I'm not sure that I can be a project maintainer. I don't know rust yet. But I can provide the best possible assistance in supporting current capabilities.

**Comment by onegreyonewhite** [comment]
@aviramha can u release new version at now for solving #128?

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Thank you.

**Pull request merged**
