### PR TITLE
add missing type Ext

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Comment by trim21** [comment]
also there is no way to get `tag` and `data` from a `Ext` object...

**Comment by exg** [comment]
Hi, thank you for the contribution. The commit need to be signed off (`git commit --signoff ...`).

**Comment by trim21** [comment]
This commit was created on GitHub.com and signed with GitHub’s verified signature.
GPG key ID: B5690EEEBB952194
Learn about vigilant mode

**Comment by exg** [comment]
> This commit was created on GitHub.com and signed with GitHub’s verified signature. GPG key ID: B5690EEEBB952194 Learn about vigilant mode

That is unrelated. This repository uses the DCO app to enforce the Developer Certificate of Origin, see https://github.com/apps/dco.

**Pull request merged**
